name: deploy_to_test_env

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "test" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # For CLI authentication
  DATABRICKS_HOST: ${{vars.DATABRICKS_PROD_HOST}}
  DATABRICKS_TOKEN: ${{secrets.DATABRICKS_PROD_TOKEN}}
  BUNDLE_ROOT: ${{ github.workspace }}/project1
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "release"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@main

      - name: Validate bundle
        run: databricks bundle validate --target prod

      - name: Deploy bundle
        continue-on-error: true
        run: databricks bundle deploy --target prod
